AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spivot Backend - FastAPI on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11

Resources:
  SpivotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Environment:
        Variables:
          # Set these in AWS Console or with --parameter-overrides
          DATABASE_URL: !Ref DatabaseUrl
          GOOGLE_API_KEY: !Ref GoogleApiKey
          CORS_ORIGINS: !Ref CorsOrigins
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection URL
    NoEcho: true
  GoogleApiKey:
    Type: String
    Description: Google Gemini API Key
    NoEcho: true
  CorsOrigins:
    Type: String
    Description: Allowed CORS origins
    Default: "*"

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
